# Generated by Django 3.1 on 2020-08-29 04:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='uuid')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='title')),
                ('sql', models.TextField(verbose_name='SQL')),
            ],
            options={
                'verbose_name': 'Query',
                'verbose_name_plural': 'Queries',
                'managed': True,
            },
        ),
    ]
