# Generated by Django 4.0.4 on 2022-05-27 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniexplorer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'managed': True, 'ordering': ['title'], 'verbose_name': 'Query', 'verbose_name_plural': 'Queries'},
        ),
    ]
